const ENDPOINT='https://api.typesafe.ai/v1/systemone';
const CATALOG={'mesh-gradient-bg':'bg','aurora-bg':'bg','scanline-crt':'bg','particle-field':'bg','dither-field-bg':'bg','warp-bands-bg':'bg','light-rays':'bg','typewriter':'text','scramble-text':'text','split-text-chars':'text','rgb-glitch-text':'text','staggered-fade-up':'text','matrix-decode':'text','wave-text':'text','fade-in':'enter','spring-in':'enter','scale-in':'enter','slide-up':'enter','blur-in':'enter','title-card':'scene','hook-card':'scene','stat-card':'scene','quote-card':'scene','end-card':'scene','lower-third':'scene','split-screen':'scene','feature-list':'scene','timeline-steps':'scene','terminal-simulator':'scene','code-reveal':'scene','pricing-card':'scene','logo-wall':'scene','chat-gpt':'scene','claude-code':'scene','media-sequence':'scene','transition-fade':'cut','transition-slide':'cut','transition-wipe':'cut','transition-whip-pan':'cut','zoom-through':'cut','intro':'comp','hero-loop':'comp','social-clip':'comp','showcase':'comp','data-story':'comp'};
function questions(){return{item_a:{type:'choice',instructions:'Pick any RemotionUI catalog item. No story role.',criteria:CATALOG},item_b:{type:'choice',instructions:'Pick a different catalog item. No story role.',criteria:CATALOG},item_c:{type:'choice',instructions:'Pick a third catalog item. No story role.',criteria:CATALOG},item_d:{type:'noul',instructions:'Include a fourth catalog item?'},item_d_which:{type:'choice',instructions:'Fourth catalog item if used.',criteria:CATALOG},seconds:{type:'score',instructions:'Length in seconds from the prompt.',criteria:['8','15','30']}};}
async function askJev(state,qs,apiKey){if(!apiKey)return heuristic(state,qs);const res=await fetch(ENDPOINT,{method:'POST',headers:{Authorization:`Bearer ${apiKey}`,'Content-Type':'application/json'},body:JSON.stringify({model:'jev-latest',state,questions:qs})});if(!res.ok)return heuristic(state,qs);return res.json();}
function hash(s){let h=0;for(let i=0;i<s.length;i++)h=(h*31+s.charCodeAt(i))|0;return h;}
function heuristic(state,qs){const p=JSON.stringify(state).toLowerCase();const answers={};for(const [id,q] of Object.entries(qs)){if(q.type==='choice'){const keys=Object.keys(q.criteria);let choice=keys[Math.abs(hash(p+id))%keys.length];if(id==='item_a'&&/crt|terminal/.test(p))choice='scanline-crt';if(id==='item_b'&&/type|text/.test(p))choice='typewriter';if(id==='item_c'&&/cli|code/.test(p))choice='terminal-simulator';const probabilities=Object.fromEntries(keys.map(k=>[k,k===choice?0.55:0.45/Math.max(1,keys.length-1)]));answers[id]={type:'choice',choice,probabilities,confidence:0.5};}else if(q.type==='score')answers[id]={type:'score',score:/30|long/.test(p)?1:/8|short/.test(p)?-0.4:0.2,confidence:0.5};else answers[id]={type:'noul',noul:0.25};}return{model:'heuristic-jev-standin',answers,usage:{input_tokens:0,output_tokens:0}};}
function secondsFrom(score){if(score>=0.6)return 30;if(score<=-0.2)return 8;return 15;}
function picksFrom(jev){const a=jev.answers||{};const ordered=[a.item_a?.choice,a.item_b?.choice,a.item_c?.choice];if((a.item_d?.noul||0)>0.5)ordered.push(a.item_d_which?.choice);const seen=new Set();return ordered.filter(s=>s&&!seen.has(s)&&seen.add(s));}
function fallbackCopy(prompt,slugs){const bits=prompt.split(/[:.,]/).map(s=>s.trim()).filter(s=>s.length>2);const out={};slugs.forEach((s,i)=>{out[s]=bits[i]||bits[0]||prompt.slice(0,42);});return out;}
async function writeCopy(prompt,slugs){const key=process.env.GROQ_API_KEY||process.env.OPENAI_API_KEY||process.env.LLM_API_KEY||'';const base=process.env.LLM_BASE_URL||(process.env.GROQ_API_KEY?'https://api.groq.com/openai/v1':'https://api.openai.com/v1');const model=process.env.LLM_MODEL||(process.env.GROQ_API_KEY?'llama-3.1-8b-instant':'gpt-4o-mini');if(!key)return{strings:fallbackCopy(prompt,slugs),model:'no-llm-key'};const res=await fetch(base.replace(/\/$/,'')+'/chat/completions',{method:'POST',headers:{Authorization:'Bearer '+key,'Content-Type':'application/json'},body:JSON.stringify({model,temperature:0.4,messages:[{role:'system',content:'Return JSON only: {"strings":{"<slug>":"..."}}. One short on-screen line per slug. No storyboard.'},{role:'user',content:'Brief:\n'+prompt+'\nSlugs:\n'+slugs.join(', ')}]})});if(!res.ok)return{strings:fallbackCopy(prompt,slugs),model,error:'llm http '+res.status};const data=await res.json();const raw=data.choices?.[0]?.message?.content||'{}';try{const json=JSON.parse(raw.replace(/^```json\n?|```$/g,''));return{strings:json.strings||json,model};}catch{return{strings:fallbackCopy(prompt,slugs),model};}}
function pascal(s){return String(s||'Comp').split(/[-_]/).map(p=>p.charAt(0).toUpperCase()+p.slice(1)).join('');}
function esc(s){return String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');}
function emitTsx(slugs,strings,seconds){const each=Math.max(20,Math.floor((seconds*30)/Math.max(1,slugs.length)));return slugs.map(s=>'// npx remotion-ui@latest add '+s).join('\n')+'\nimport { AbsoluteFill } from "remotion";\nexport const PromptVideo = () => (\n  <AbsoluteFill>\n'+slugs.map(s=>'    <'+pascal(s)+' text='+JSON.stringify(strings[s]||'')+' durationInFrames={'+each+'} />').join('\n')+'\n  </AbsoluteFill>\n);\n';}
function previewHtml(slugs,strings,seconds){const hold=Math.max(1.2,seconds/Math.max(1,slugs.length));return '<!doctype html><html><style>body{margin:0;background:#0b1020;color:#fff;font-family:system-ui}.stage{position:relative;aspect-ratio:16/9}.layer{position:absolute;inset:0;display:flex;flex-direction:column;justify-content:center;padding:48px;opacity:0;animation:h '+hold+'s ease both}'+slugs.map((_,i)=>'#s'+i+'{animation-delay:'+(i*hold)+'s}').join('')+'@keyframes h{0%{opacity:0}12%{opacity:1}86%{opacity:1}100%{opacity:0}}.slug{color:#7C9CFF;font:11px monospace}</style><body><div class=stage>'+slugs.map((s,i)=>'<div class=layer id=s'+i+'><div class=slug>'+esc(s)+'</div><h1>'+esc(strings[s]||'')+'</h1></div>').join('')+'</div></body></html>';}
export default async function handler(req,res){res.setHeader('Access-Control-Allow-Origin','*');if(req.method==='OPTIONS')return res.status(204).end();if(req.method!=='POST')return res.status(405).json({error:'POST only'});const prompt=String(req.body?.prompt||'').trim();if(!prompt)return res.status(400).json({error:'prompt required'});const t0=Date.now();const jev=await askJev({user_prompt:prompt,catalog:'https://remotionui.com/docs/components/browse'},questions(),process.env.TYPESAFE_API_KEY||'');const tJev=Date.now();const slugs=picksFrom(jev);const seconds=secondsFrom(jev.answers?.seconds?.score||0);const copy=await writeCopy(prompt,slugs);const tCopy=Date.now();const spec={meta:{prompt,model:jev.model,catalog:'https://remotionui.com/docs/components/browse',seconds,fps:30,width:1920,height:1080,durationInFrames:seconds*30,copyModel:copy.model,usage:jev.usage},jev:Object.fromEntries(Object.entries(jev.answers||{}).map(([k,v])=>[k,{type:v.type,choice:v.choice,score:v.score,noul:v.noul,confidence:v.confidence}])),slugs,strings:copy.strings,remotionTsx:emitTsx(slugs,copy.strings,seconds)};spec.previewHtml=previewHtml(slugs,copy.strings,seconds);spec.timing={jevMs:tJev-t0,copyMs:tCopy-tJev,assembleMs:Date.now()-tCopy,totalMs:Date.now()-t0};return res.status(200).json(spec);}
