const ENDPOINT = "https://api.typesafe.ai/v1/systemone";
const SCENES = {"title-card":"Full-screen title.","hook-card":"Opening hook.","stat-card":"One big metric.","quote-card":"Pull quote.","end-card":"Closing CTA.","lower-third":"Name overlay.","split-screen":"Two-column compare.","feature-list":"Feature rows.","timeline-steps":"How-it-works steps.","terminal-simulator":"CLI typing.","code-reveal":"Code reveal.","code-diff-wipe":"Diff wipe.","pricing-card":"Price + CTA.","comparison-table":"Feature table.","logo-wall":"Logo grid.","chat-gpt":"ChatGPT thread.","claude-code":"Claude Code session.","media-sequence":"B-roll stack."};
const BACKGROUNDS = {"mesh-gradient-bg":"Mesh gradient.","aurora-bg":"Aurora wash.","caustics-bg":"Caustics.","animated-noise-grain":"Grain.","particle-field":"Particles.","light-rays":"God rays.","scanline-crt":"CRT scanlines.","dither-field-bg":"Dither shader.","grain-gradient-bg":"Grain gradient.","warp-bands-bg":"Warp bands."};
const TEXTFX = {"typewriter":"Type on.","scramble-text":"Scramble.","split-text-chars":"Split chars.","wave-text":"Wave.","rgb-glitch-text":"RGB glitch.","neon-flicker-text":"Neon flicker.","handwriting-text":"Handwriting.","matrix-decode":"Matrix decode.","staggered-fade-up":"Stagger fade.","stroke-to-fill-text":"Stroke to fill."};
const ENTER = {"fade-in":"Fade in.","spring-in":"Spring pop.","scale-in":"Scale in.","slide-up":"Slide up.","slide-left":"Slide left.","blur-in":"Blur in.","rotate-in":"Rotate in.","tracking-in":"Tracking in."};
const TRANSITIONS = {"transition-fade":"Crossfade.","transition-slide":"Slide.","transition-wipe":"Wipe.","transition-whip-pan":"Whip pan.","blur-reveal":"Blur reveal.","directional-wipe":"Directional wipe.","circle-reveal":"Circle reveal.","zoom-through":"Zoom through.","transition-light-leak":"Light leak."};
const COMPOSITIONS = {"intro":"Intro.","hero-loop":"Hero loop.","social-clip":"Social clip.","showcase":"Showcase.","data-story":"Data story.","deploy-reveal":"Deploy reveal.","landing-code-showcase":"Landing + code.","creator-reel":"Creator reel.","tutorial-clip":"Tutorial.","podcast-clip":"Podcast."};
function questions(){return{composition:{type:"choice",instructions:"RemotionUI composition.",criteria:COMPOSITIONS},background:{type:"choice",instructions:"RemotionUI background primitive.",criteria:BACKGROUNDS},text_fx:{type:"choice",instructions:"RemotionUI text primitive.",criteria:TEXTFX},enter:{type:"choice",instructions:"RemotionUI enter primitive.",criteria:ENTER},scene_0:{type:"choice",instructions:"Opening RemotionUI scene.",criteria:SCENES},scene_1:{type:"choice",instructions:"Second RemotionUI scene.",criteria:SCENES},scene_2:{type:"choice",instructions:"Third RemotionUI scene.",criteria:SCENES},scene_3:{type:"choice",instructions:"Close RemotionUI scene.",criteria:SCENES},transition:{type:"choice",instructions:"RemotionUI transition.",criteria:TRANSITIONS},use_lower_third:{type:"noul",instructions:"Overlay lower-third?"},density:{type:"score",instructions:"How many scenes?",criteria:["2","3","4"]}};}
async function askJev(state,qs,apiKey){if(!apiKey)return heuristic(state,qs);const res=await fetch(ENDPOINT,{method:"POST",headers:{Authorization:`Bearer ${apiKey}`,"Content-Type":"application/json"},body:JSON.stringify({model:"jev-latest",state,questions:qs})});if(!res.ok)return heuristic(state,qs);return res.json();}
function heuristic(state,qs){const p=JSON.stringify(state).toLowerCase();const answers={};for(const [id,q] of Object.entries(qs)){if(q.type==="choice"){const keys=Object.keys(q.criteria);let choice=keys[0];if(id==="composition")choice=/social|short/.test(p)?"social-clip":/data/.test(p)?"data-story":"intro";if(id==="background")choice=/crt|terminal/.test(p)?"scanline-crt":"mesh-gradient-bg";if(id==="text_fx")choice=/glitch/.test(p)?"rgb-glitch-text":/type|cli/.test(p)?"typewriter":"split-text-chars";if(id==="enter")choice=/punch|pop/.test(p)?"spring-in":"fade-in";if(id==="scene_0")choice=/cli|terminal|jev/.test(p)?"terminal-simulator":"title-card";if(id==="scene_1")choice=/step|loop/.test(p)?"timeline-steps":"feature-list";if(id==="scene_2")choice=/stat/.test(p)?"stat-card":"split-screen";if(id==="scene_3")choice="end-card";if(id==="transition")choice=/whip/.test(p)?"transition-whip-pan":"transition-fade";const probabilities=Object.fromEntries(keys.map(k=>[k,k===choice?0.7:0.3/Math.max(1,keys.length-1)]));answers[id]={type:"choice",choice,probabilities,confidence:0.55};}else if(q.type==="score")answers[id]={type:"score",score:1,confidence:0.5};else answers[id]={type:"noul",noul:0.2};}return{model:"heuristic-jev-standin",answers,usage:{input_tokens:0,output_tokens:0}};}
function titleFrom(prompt){const q=prompt.match(/"([^"]+)"/);if(q)return q[1];const f=prompt.match(/for ([A-Z][^,:]{2,40})/);if(f)return f[1].trim();return prompt.split(/[:.]/)[0].slice(0,48);}
function pascal(slug){return String(slug||"Comp").split(/[-_]/).map(s=>s.charAt(0).toUpperCase()+s.slice(1)).join("");}
function esc(s){return String(s??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll("`","").replaceAll('"',"'");}
function assemble(prompt,jev){const a=jev.answers||{};const count=Math.min(4,Math.max(2,2+Math.round(a.density?.score||1)));const slots=["scene_0","scene_1","scene_2","scene_3"].slice(0,count);const used=new Set();const fallback=["title-card","feature-list","stat-card","end-card"];const title=titleFrom(prompt);const clips=[];let from=0;slots.forEach((id,i)=>{let slug=a[id]?.choice||fallback[i];if(i===slots.length-1)slug=a.scene_3?.choice||"end-card";if(used.has(slug)&&slug!=="timeline-steps")slug=fallback.find(s=>!used.has(s))||slug;used.add(slug);clips.push({id,slug,install:"npx remotion-ui@latest add "+slug,from,durationInFrames:60,text:title,jev:{confidence:a[id]?.confidence}});from+=52;});const picks={composition:a.composition?.choice,background:a.background?.choice,text_fx:a.text_fx?.choice,enter:a.enter?.choice,transition:a.transition?.choice};return{meta:{prompt,model:jev.model,catalog:"https://remotionui.com/docs/components/browse",fps:30,width:1920,height:1080,durationInFrames:from+8,usage:jev.usage,...picks},jev:Object.fromEntries(Object.entries(a).map(([k,v])=>[k,{type:v.type,choice:v.choice,score:v.score,noul:v.noul,confidence:v.confidence}])),picks,clips,remotionTsx:emitTsx(picks,clips,title)};}
function emitTsx(picks,clips,title){const scenes=clips.filter(c=>!c.overlay);const slugs=[picks.background,picks.text_fx,picks.enter,picks.transition,...scenes.map(c=>c.slug)].filter(Boolean);return slugs.map(s=>"// npx remotion-ui@latest add "+s).join("\n")+`\nimport { AbsoluteFill } from \"remotion\";\nimport { TransitionSeries } from \"@remotion/transitions\";\nexport const PromptVideo = () => (\n  <AbsoluteFill>\n    <TransitionSeries>\n${scenes.map(c=>"      <TransitionSeries.Sequence durationInFrames={"+c.durationInFrames+"}><"+pascal(c.slug)+" title=\""+esc(title)+"\" /></TransitionSeries.Sequence>").join("\n")}\n    </TransitionSeries>\n  </AbsoluteFill>\n);\n`;}
function previewHtml(spec){const scenes=spec.clips.filter(c=>!c.overlay);return `<!doctype html><html><style>body{margin:0;background:#0b1020;color:#fff;font-family:system-ui}.stage{position:relative;aspect-ratio:16/9}.layer{position:absolute;inset:0;display:flex;flex-direction:column;justify-content:center;padding:48px;opacity:0;animation:h 1.7s ease both}${scenes.map((_,i)=>"#s"+i+"{animation-delay:"+(i*1.7)+"s}").join("")}@keyframes h{0%{opacity:0}15%{opacity:1}85%{opacity:1}100%{opacity:0}}.slug{color:#7C9CFF;font:11px monospace}</style><body><div class=stage>${scenes.map((c,i)=>"<div class=layer id=s"+i+"><div class=slug>"+esc(c.slug)+"</div><h1>"+esc(c.text)+"</h1><div class=slug>"+esc(c.install)+"</div></div>").join("")}</div></body></html>`;}
export default async function handler(req,res){res.setHeader("Access-Control-Allow-Origin","*");if(req.method==="OPTIONS")return res.status(204).end();if(req.method!=="POST")return res.status(405).json({error:"POST only"});const prompt=String(req.body?.prompt||"").trim();if(!prompt)return res.status(400).json({error:"prompt required"});const t0=Date.now();const jev=await askJev({user_prompt:prompt,catalog:"https://remotionui.com/docs/components/browse"},questions(),process.env.TYPESAFE_API_KEY||"");const tJev=Date.now();const spec=assemble(prompt,jev);spec.previewHtml=previewHtml(spec);spec.timing={jevMs:tJev-t0,assembleMs:Date.now()-tJev,totalMs:Date.now()-t0};return res.status(200).json(spec);}
